#!/bin/bash
#Ogg-Converter
#By Andreo Rissardo

echo "Convertendo pra ogg"
echo "Aguarde!!!"
mkdir ogg-music
cp *.mp3 ogg-music
cd ogg-music
for f in ./*.mp3; do ffmpeg -i "$f" -c:a libvorbis -q:a 192k "${f/%mp3/ogg}"; done
rm -rf *.mp3

echo "Pronto!!!"
